stack: wunder/wundena
version: 1.0.1

variables:
  drupal-mysql-root:
    type: string
    from:
      vault: drupal-mysql-root
      random_string: 32
    to:
      vault: drupal-mysql-root
  drupal-mysql-password:
    type: string
    from:
      vault: drupal-mysql-password
      random_string: 32
    to:
      vault: drupal-mysql-password
  project:
    type: string
    from:
      env: CIRCLE_PROJECT_REPONAME
  branch:
    type: string
    from:
      env: BRANCH_SLUG
  sha1:
    type: string
    from:
      env: CIRCLE_SHA1

services:
  drupal_lb:
    image: kontena/lb:latest
    ports:
      - 80:80
      - 443:443
    deploy:
      strategy: daemon
    certificates:
      - subject: wundena.dev.wunder.io
        type: env
        name: SSL_CERT_wundena.dev.wunder.io
  drupal_nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.2
    instances: 3
    depends_on:
      - drupal
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: drupal
      NGINX_SERVER_ROOT: /var/www/html/web
      KONTENA_LB_VIRTUAL_HOSTS: ${branch}.${project}.wundena.dev.wunder.io
      KONTENA_LB_MODE: http
      KONTENA_LB_BALANCE: roundrobin
      KONTENA_LB_INTERNAL_PORT: 80
      KONTENA_LB_CUSTOM_SETTINGS: |
        redirect scheme https code 301 if !{ ssl_fc }
    links:
      - drupal_lb
    volumes_from:
      - drupal-%s
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_USER: root
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
      KONTENA_LB_MODE: http
      KONTENA_LB_BALANCE: roundrobin
      KONTENA_LB_INTERNAL_PORT: 80
      KONTENA_LB_CUSTOM_SETTINGS: |
        redirect scheme https code 301 if !{ ssl_fc }
      KONTENA_LB_VIRTUAL_PATH: /pma
    secrets:
      - secret: drupal-mysql-root
        name: PMA_PASSWORD
        type: env
    links:
      - drupal_lb
  drupal:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: "images.kontena.io/wunder/drupal-${project}:${sha1}"
    instances: 3
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      DB_USER_DRUPAL: drupal
      DB_NAME_DRUPAL: drupal
      DB_HOST_DRUPAL: database
    secrets:
      - secret: drupal-mysql-password
        name: DB_PASS_DRUPAL
        type: env
      - secret: BASIC_AUTH_WUNDENA
        name: KONTENA_LB_BASIC_AUTH_SECRETS
        type: env
    volumes:
      - drupal_files:/var/www/html/web/sites/default/files
      - /var/www/html/web
  database:
    image: mariadb:10.1
    stateful: true
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
    secrets:
      - secret: drupal-mysql-root
        name: MYSQL_ROOT_PASSWORD
        type: env
      - secret: drupal-mysql-password
        name: MYSQL_PASSWORD
        type: env
volumes:
  drupal_files:
    external: true
