stack: wunder/drupal

variables:
  drupal-mysql-root:
    type: string
    from:
      vault: ${STACK}-mysql-root
      random_string: 32
    to:
      vault: ${STACK}-mysql-root
  drupal-mysql-password:
    type: string
    from:
      vault: ${STACK}-mysql-password
      random_string: 32
    to:
      vault: ${STACK}-mysql-password
  basicauth_credentials:
    type: string
    from:
      vault: ${STACK}_basic_auth
      prompt: Basicauth credentials (user [username] insecure-password [password])
    to:
      vault: ${STACK}_basic_auth
  virtualhost:
    type: string
    from:
      env: VIRTUALHOST
      prompt: Virtualhost
  loadbalancer:
    type: string
    required: true
    from:
      env: LOADBALANCER
      service_link:
        prompt: Choose a loadbalancer
        image: kontena/lb
services:
  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.2
    instances: 2
    depends_on:
      - drupal
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: drupal
      NGINX_SERVER_ROOT: /var/www/html/web
      KONTENA_LB_MODE: http
      KONTENA_LB_BALANCE: roundrobin
      KONTENA_LB_INTERNAL_PORT: 80
      KONTENA_LB_VIRTUAL_HOSTS: "{{ virtualhost }}"
      KONTENA_LB_CUSTOM_SETTINGS: |
        redirect scheme https code 301 if !{ ssl_fc }
    links:
      - {{ loadbalancer }}
    volumes_from:
      - drupal-%s
  drupal:
    image: images.kontena.io/wunder/wundena:1
    instances: 2
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      DB_USER_DRUPAL: drupal
      DB_NAME_DRUPAL: drupal
      DB_HOST_DRUPAL: database
    secrets:
      - secret: ${STACK}-mysql-password
        name: DB_PASS_DRUPAL
        type: env
        # {% if basicauth_credentials %}
      - secret: "${STACK}_basic_auth"
        name: KONTENA_BASIC_AUTH_SECRETS
        type: env
        # {% endif %}
    volumes:
      - drupal_files:/var/www/html/web/sites/default/files
      - /var/www/html/web
  database:
    image: mariadb:10.2
    stateful: true
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
    secrets:
      - secret: ${STACK}-mysql-root
        name: MYSQL_ROOT_PASSWORD
        type: env
      - secret: ${STACK}-mysql-password
        name: MYSQL_PASSWORD
        type: env
volumes:
  drupal_files:
    external:
      name: ${STACK}_files
