defaults: &defaults
  docker:
    - image: wunderio/circleci-builder
      environment:
        - DB_HOST_DRUPAL=localhost
        - DB_NAME_DRUPAL=drupal
        - DB_USER_DRUPAL=drupal
        - DB_PASS_DRUPAL=
    - image: circleci/mariadb:10
      environment:
        - MYSQL_USER=drupal
        - MYSQL_DATABASE=drupal

version: 2
jobs:
  build:
    <<: *defaults

    working_directory: ~/repo

    steps:
      - checkout

      - run: cd drupal && phpcs --standard=phpcs.xml

      - restore_cache:
          keys: [v1-dependencies-{{ checksum "drupal/composer.lock" }}]

      - run: cd drupal && composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./drupal/vendor
            - ./drupal/web/core
            - ./drupal/web/modules/contrib
            - ./drupal/web/themes/contrib
            - ./drupal/web/profiles/contrib
            - ./drupal/web/libraries
          key: v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - run: cd drupal/web && drush status
