version: 2
jobs:
  build:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: cd drupal && phpcs --standard=phpcs.xml

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - run: cd drupal && composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./drupal/vendor
            - ./drupal/web/core
            - ./drupal/web/modules/contrib
            - ./drupal/web/themes/contrib
            - ./drupal/web/profiles/contrib
            - ./drupal/web/libraries
          key: v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - run: cd drupal/web && drush status

      - setup_remote_docker

      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t images.kontena.io/wunder/wundena:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS         # (5)
          docker push images.kontena.io/wunder/wundena:$TAG