version: 2
jobs:
  build:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: cd drupal && phpcs --standard=phpcs.xml

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - run: cd drupal && composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./drupal/vendor
            - ./drupal/web/core
            - ./drupal/web/modules/contrib
            - ./drupal/web/themes/contrib
            - ./drupal/web/profiles/contrib
            - ./drupal/web/libraries
          key: v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - run: cd drupal/web && drush status

      - setup_remote_docker

      # build and push Docker image
      - run: |
          cd drupal
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker login -u $KONTENA_DOCKER_USER -p $KONTENA_DOCKER_PASSWORD images.kontena.io

          # Build the images and push them to the repository.
          kontena stack build

      # Push the stack to the registry and deploy it.
      - run: |
          cd drupal

          STACK_VERSION=`awk '/version:/{print $NF}' kontena.yml`
          STACK_NAME=`awk '/stack:/{print $NF}' kontena.yml`

          # Create the stack if needed
          if [[ ! $(kontena stack registry show --versions $STACK_NAME) =~ "$STACK_VERSION" ]];
          then
            kontena stack registry push kontena.yml;
          fi

          DEPLOYED_STACK_NAME="$CIRCLE_PROJECT_REPONAME-${CIRCLE_BRANCH//\//-}"

          # Check if the stack is already deployed
          if [[ ! `kontena stack show $DEPLOYED_STACK_NAME` ]];
          then
            # Install the stack
            kontena stack install --name $DEPLOYED_STACK_NAME $STACK_NAME:$STACK_VERSION
          else
            # Or upgrade an existing stack
            kontena stack upgrade $DEPLOYED_STACK_NAME $STACK_NAME:$STACK_VERSION
          fi

