version: 2
jobs:
  build:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: cd drupal && phpcs --standard=phpcs.xml

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - run: cd drupal && composer install -n --prefer-dist --ignore-platform-reqs

      - save_cache:
          paths:
            - ./drupal/vendor
            - ./drupal/web/core
            - ./drupal/web/modules/contrib
            - ./drupal/web/themes/contrib
            - ./drupal/web/profiles/contrib
            - ./drupal/web/libraries
          key: v1-dependencies-{{ checksum "drupal/composer.lock" }}

      - setup_remote_docker

      # build and push Docker image
      - run: |
          cd drupal

          docker login -u $KONTENA_DOCKER_USER -p $KONTENA_DOCKER_PASSWORD images.kontena.io

          JIRA_ID_REGEX='/\d+-[A-Z]+(?!-?[a-zA-Z]{1,10})/g'

          BRANCH_SLUG="${CIRCLE_BRANCH//\//-}"

          if [ $CIRCLE_PROJECT_REPONAME =~ $JIRA_ID_REGEX ]
          then
            STACK_NAME="$?-$BRANCH_SLUG"
          else
            STACK_NAME="$CIRCLE_PROJECT_REPONAME-$BRANCH_SLUG"
          fi

          # Build the images and push them to the repository.
          kontena stack build --name $STACK_NAME -v branch=$BRANCH_SLUG

  deploy:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: |
          cd drupal

          BRANCH_SLUG="${CIRCLE_BRANCH//\//-}"

          if [ $CIRCLE_PROJECT_REPONAME =~ $JIRA_ID_REGEX ]
          then
            STACK_NAME="$?-$BRANCH_SLUG"
          else
            STACK_NAME="$CIRCLE_PROJECT_REPONAME-$BRANCH_SLUG"
          fi

          kontena stack install --name $STACK_NAME -v branch=$BRANCH_SLUG || kontena stack upgrade -v branch=$BRANCH_SLUG $STACK_NAME

          kontena service exec $STACK_NAME/drupal drush status --root=/var/www/html/web

  updb:
    docker:
      - image: wunderio/circleci-builder

    steps:
      - checkout

      - run: |
          cd drupal

          BRANCH_SLUG="${CIRCLE_BRANCH//\//-}"

          if [ $CIRCLE_PROJECT_REPONAME =~ $JIRA_ID_REGEX ]
          then
            STACK_NAME="$?-$BRANCH_SLUG"
          else
            STACK_NAME="$CIRCLE_PROJECT_REPONAME-$BRANCH_SLUG"
          fi

          kontena service exec $STACK_NAME/drupal drush updb -y

          kontena service exec $STACK_NAME/drupal drush co -y

workflows:
  version: 2
  commit:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - updb:
          requires:
            - deploy
