---
# Example site.yml

# The default environment is our local development environment.
# Note that the the default site is used as a base for all sites, so whatever you define here are inherited to
# other site definitions.
default:

  # An alias or aliases for the site, this could also be:
  # aliases:
  #   - vagrant
  #   - mylocalbox
  aliases:
    - vagrant
    - local

  # Omit makefile to leave out drush
  # makefile: conf/site.make
  type: composer

  # Installation profile to use
  profile: config_installer

  drupal_version: d8

  # Site name given at installation phase
  site: Wundena

  # In development environments we usually want to use symlinks, note the settings.php linking
  link:
    - files: web/sites/default/files

  local_commands:
    new:
      - shell: echo "Use the 'create' command to create a new project and the 'reset' command to join an existing one."

    create:
      - verify: "Type yes to verify you want to create a new installation: "
      - make
      - cleanup

    build:
      - make

    update:
      - drush: updb -y
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup

    deploy:
      - shell: 
        - docker build -f Dockerfile.prod -t images.kontena.io/wunder/wundena:1 .
        - docker push images.kontena.io/wunder/wundena:1
        - kontena stack upgrade wundena

dev:

  link:
    - /drupal_files: web/sites/default/files


  local_commands:
    new:
      - shell: echo "Use the 'create' command to create a new project and the 'reset' command to join an existing one."

    create:
      - verify: "Type yes to verify you want to create a new installation: "
      - make
      - cleanup

    backup:
      - backup:
         ignore:
          - builds
          - web/sites/default/files

    build:
      - shell: echo "No build step needed in this environment, just run 'update'."

    update:
      - shell: chmod -R a+w web
      - make
      - drush: updb -y
      - drush: cim -y
      - drush: entity-updates -y
      - cleanup
      - shell: chmod -R a-w web
      - shell: sudo systemctl restart nginx php-fpm varnish

prod:

  link:
    - files: web/sites/default/files


  create:
    - shell: echo "Creating a new installation should only be done in local environments."

  build:
    - make

  update:
    - drush: updb -y
    - drush: cim -y
    - drush: entity-updates -y
    - cleanup
    - shell: chmod -R a-w web
    - shell: sudo systemctl restart nginx php-fpm varnish
